spring:
  application:
    name: uaa-service

# Define the port where the UAA server would be running
server:
  port: 8802

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# Define security
security:
  basic:
    enabled: false
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level.org.springframework.security: DEBUG

flyway:
  locations: classpath:db/migration
---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}
