version: "2"
services:
 
  service-registry:
    image: pzeszko/service-registry
    environment:
      JAVA_OPTS: -Xms450m -Xmx450m
      SERVICE_HOST: registry
      SERVICE_PORT: 8761

  uaa-service:
    image: pzeszko/uaa-service
    environment:
      SERVICE_PORT: 8802
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms350m -Xmx350m

  api-gateway:
    image: pzeszko/api-gateway
    environment:
      SERVICE_PORT: 8765
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
    ports:
      - "8765:8765"
    
  clothes-service:
    image: pzeszko/clothes-service
    environment:
      SERVICE_PORT: 8803
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms700m -Xmx700m
   
   
  user-service:
    image: pzeszko/user-service
    environment:
      SERVICE_PORT: 8871
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms300m -Xmx300m
      
  price-service:
    image: pzeszko/price-service
    environment:
      SERVICE_PORT: 8805
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
      
  account-service:
    image: pzeszko/account-service
    environment:
      REGISTRY_URL: http://service-registry:8761/eureka
      SERVICE_PORT: 8801
      JAVA_OPTS: -Xms500m -Xmx500m

  stock-service:
    image: pzeszko/stock-service
    environment:
      SERVICE_PORT: 8806
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
      
  image-service:
    image: pzeszko/image-service
    environment:
      SERVICE_PORT: 8807
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
  
  order-service:
    image: pzeszko/order-service
    environment:
      SERVICE_PORT: 8805
      REGISTRY_URL: http://service-registry:8761/eureka
  
      