version: "2"
services:
 
  service-registry:
    image: pzeszko/service-registry
    environment:
      JAVA_OPTS: -Xms450m -Xmx450m
      SERVICE_HOST: registry
      SERVICE_PORT: 8761
    ports:
      - "8761:8761"

  api-gateway:
    image: pzeszko/api-gateway
    environment:
      SERVICE_PORT: 8765
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
    ports:
      - "8765:8765"
    
  clothes-service:
    image: pzeszko/clothes-service
    environment:
      SERVICE_PORT: 8803
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms700m -Xmx700m
   
   
  user-service:
    image: pzeszko/user-service
    environment:
      SERVICE_PORT: 8871
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms300m -Xmx300m
      
 
  turbine-service:
    image: pzeszko/turbine-service
    environment:
      SERVICE_PORT: 8989
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
    ports:
      - "8989:8989"
      
  monitor-service:
    image: pzeszko/monitor-service
    environment:
      SERVICE_PORT: 7979
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms500m -Xmx500m
    ports:
      - "7979:7979"
      
  image-service:
    image: pzeszko/image-service
    environment:
      SERVICE_PORT: 8421
      REGISTRY_URL: http://service-registry:8761/eureka
      JAVA_OPTS: -Xms300m -Xmx300m
      
  
      